springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
  packages-to-scan: "*"
  paths-to-match: "*"



